import 'angular/angular.js';
import 'angular-ui-router';
import './app.module.js';
import './routes.js';
import './main/main.directive';
import './counter/counter.component.js';
import './hello/hello.directive.js';
import './emoji/emoji.component.js';
import './fade/fade.component.js';
